# Generated by Django 6.0.6 on 2026-09-27 21:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def backfill_subtotals(apps, schema_editor):
    """Orders placed before discounts existed paid full price: subtotal = total."""
    Order = apps.get_model("orders", "Order")
    Order.objects.update(subtotal=models.F("total"))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code_text',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_subtotals, migrations.RunPython.noop),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='What customers type, e.g. SPRING20. Not case-sensitive.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Use only letters, numbers, and hyphens.')])),
                ('percent_off', models.PositiveSmallIntegerField(help_text='A whole number from 1 to 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('applies_to', models.CharField(choices=[('ORDER', 'Entire order'), ('PRODUCTS', 'Specific products')], default='ORDER', max_length=8)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('products', models.ManyToManyField(blank=True, related_name='discount_codes', to='products.product')),
            ],
            options={
                'ordering': ['-starts_at', 'code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discountcode'),
        ),
    ]
