# Generated by Django 6.0.6 on 2026-10-04 22:44

import products.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, editable=False, max_length=255, upload_to=products.images.product_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='image_original',
            field=models.ImageField(blank=True, editable=False, max_length=255, upload_to=products.images.product_original_path),
        ),
    ]
